stfc-cloud-fission:
  fission-all:
    routerServiceType: ClusterIP

    router:
      ingress:
        enabled: true
        ingressClassName: ingress-nginx-external

        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          cert-manager.io/cluster-issuer: self-signed

        hosts:
          - host: fission.david-epa.nubes.stfc.ac.uk
            paths:
              - path: /
                pathType: Prefix

        tls:
          - secretName: fission-router-tls
            hosts:
              - fission.david-epa.nubes.stfc.ac.uk

    
    openTelemetry:
      otlpCollectorEndpoint: "otel-collector.opentelemetry-operator-system.svc:4317"

    additionalFissionNamespaces: [fission]
    
    webhook:
      certManager:
        enabled: true

    serviceMonitor:
      enabled: true
      namespace: "monitoring-system"
      additionalServiceMonitorLabels:
        release: "kube-prometheus-stack"
    podMonitor:
      enabled: true
      namespace: "monitoring-system"
      additionalPodMonitorLabels:
        release: "kube-prometheus-stack"
    grafana:
      namespace: "monitoring-system"
      dashboards:
        enable: true