stfc-cloud-fission:
  fission-all:
    routerServiceType: ClusterIP
    
    openTelemetry:
      otlpCollectorEndpoint: "otel-collector.opentelemetry-operator-system.svc:4317"

    additionalFissionNamespaces: [fission]
    
    webhook:
      certManager:
        enabled: true
   
    poolmgr:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8888"

    serviceMonitor:
      enabled: true
      namespace: "monitoring-system"
      additionalServiceMonitorLabels:
        release: "kube-prometheus-stack"
    podMonitor:
      enabled: true
      namespace: "monitoring-system"
      additionalPodMonitorLabels:
        release: "kube-prometheus-stack"
    grafana:
      namespace: "monitoring-system"
      dashboards:
        enable: true