stfc-cloud-openstack-cluster:
  openstack-cluster:
    machineSSHKeyName: k8s-david-epa
    cloudCredentialsSecretName: david-epa-cluster-cloud-credentials

    kubernetesVersion: "1.34.3"
    machineImage: "capi-ubuntu-2204-kube-v1.34.3"

    controlPlane:
      machineFlavor: dep-l2.tiny

    nodeGroups:
      - name: default-md-0
        machineCount: 2
        machineFlavor: l3.nano

    nodeGroupDefaults:
      machineFlavor: dep-l2.xsmall
      nodeLabels:
        # we're running longhorn on this cluster
        # set label so worker nodes can host longhorn volumes
        longhorn.store.nodeselect/longhorn-storage-node: true

    addons:
      # defrag etcd every day at 1:12pm
      etcdDefrag:
        release:
          values:
            schedule: 1 12 * * * # smearing the time for defrag job 1:12pm daily
